/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { SongChordService } from "../songChord.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { SongChordCreateInput } from "./SongChordCreateInput";
import { SongChord } from "./SongChord";
import { SongChordFindManyArgs } from "./SongChordFindManyArgs";
import { SongChordWhereUniqueInput } from "./SongChordWhereUniqueInput";
import { SongChordUpdateInput } from "./SongChordUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class SongChordControllerBase {
  constructor(
    protected readonly service: SongChordService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: SongChord })
  @nestAccessControl.UseRoles({
    resource: "SongChord",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: SongChordCreateInput,
  })
  async createSongChord(
    @common.Body() data: SongChordCreateInput
  ): Promise<SongChord> {
    return await this.service.createSongChord({
      data: {
        ...data,

        chord: data.chord
          ? {
              connect: data.chord,
            }
          : undefined,

        song: data.song
          ? {
              connect: data.song,
            }
          : undefined,
      },
      select: {
        chord: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        position: true,

        song: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [SongChord] })
  @ApiNestedQuery(SongChordFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "SongChord",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async songChords(@common.Req() request: Request): Promise<SongChord[]> {
    const args = plainToClass(SongChordFindManyArgs, request.query);
    return this.service.songChords({
      ...args,
      select: {
        chord: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        position: true,

        song: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: SongChord })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "SongChord",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async songChord(
    @common.Param() params: SongChordWhereUniqueInput
  ): Promise<SongChord | null> {
    const result = await this.service.songChord({
      where: params,
      select: {
        chord: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        position: true,

        song: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: SongChord })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "SongChord",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: SongChordUpdateInput,
  })
  async updateSongChord(
    @common.Param() params: SongChordWhereUniqueInput,
    @common.Body() data: SongChordUpdateInput
  ): Promise<SongChord | null> {
    try {
      return await this.service.updateSongChord({
        where: params,
        data: {
          ...data,

          chord: data.chord
            ? {
                connect: data.chord,
              }
            : undefined,

          song: data.song
            ? {
                connect: data.song,
              }
            : undefined,
        },
        select: {
          chord: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          id: true,
          position: true,

          song: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: SongChord })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "SongChord",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteSongChord(
    @common.Param() params: SongChordWhereUniqueInput
  ): Promise<SongChord | null> {
    try {
      return await this.service.deleteSongChord({
        where: params,
        select: {
          chord: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          id: true,
          position: true,

          song: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
